name: "Sphinx: Render docs"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - id: sphinx
        uses: sphinx-notes/pages@v3
        with:
          publish: false
          documentation_path: ./docs/source

      - uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ steps.sphinx.outputs.artifact }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
